language: node_js
node_js:
  - "8.11.4"
script:
  - npm run production
on:
  branch: master
sudo: required
services:
  - docker
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
